name: Android CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Install Gradle
        run: sudo apt update && sudo apt install -y gradle

      - name: Show project files
        run: ls -R

      - name: Build Debug APK
        run: gradle :app:assembleDebug
